<?php

/** @var Magento\Framework\View\Element\Template $block */
$page = $block->getRequest()->getParam('page') ?? 1;
$total = $block->getData('viewModel')->getTotalPostsCount();
?>

<div class="blog-container" data-bind="scope: 'blog'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "blog": {
                            "component": "Magespace_Blog/js/blog",
                            "posts": [],
                            "total": <?= $total ?>,
                            "page": <?= $page ?>
                        }
                    }
                }
             }
    }
</script>
