<?php
/** @var Magento\Framework\View\Element\Template $block */
?>
<?php if ($block->isPost()) : ?>
    <div class="comments-container">
        <hr>
        <h3>Comments</h3>
        <br>
        <div class="post-comments-container" data-bind="scope: 'post_comments'">
            <!-- ko template: getTemplate() --><!-- /ko -->
        </div>
        <hr>
        <br>
        <div class="comment-form-container" data-bind="scope: 'comment_form'">
            <!-- ko template: getTemplate() --><!-- /ko -->
        </div>
    </div>

    <script type="text/x-magento-init">
    {
        "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "post_comments": {
                            "component": "Magespace_PostComment/js/post_comments",
                            "comments": <?= $block->getCommentsJson(); ?>
                        }
                    }
                }
             }
    }
    </script>
    <?php if ($block->isCustomerLoggedIn()) : ?>
        <script type="text/x-magento-init">
            {
                "*": {
                        "Magento_Ui/js/core/app": {
                            "components": {
                                "comment_form": {
                                    "component": "Magespace_PostComment/js/comment_form"
                                }
                            }
                        }
                    }
            }

        </script>
    <?php else : ?>
        <div>Log in to comment</div>
    <?php endif ?>
<?php endif ?>
