<?php
/** @var Magento\Framework\View\Element\Template $block */
?>
<?php if ($block->isPost()) : ?>
    <div class="comments-container">
        <hr>
        <h3>Comments</h3>
        <br>
        <div class="post-comments-container" data-bind="scope: 'post_comments'">
            <!-- ko template: getTemplate() --><!-- /ko -->
        </div>
    </div>

    <script type="text/x-magento-init">
    {
        "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "post_comments": {
                            "component": "Magespace_PostComment/js/post_comments",
                            "comments": <?= $block->getCommentsJson(); ?>
                        }
                    }
                }
             }
    }
    </script>
<?php endif ?>
